name: CI Pipeline - Karsajobs

on:
  push:
    branches:
      - karsajobs

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install and Run hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile

  test-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.15

    - name: Run Unit Tests
      run: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build and Push Docker Image
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
      run: ./build_push_image_karsajobs.sh
